"""Pytest fixtures + isolation harness for the RAG backend suite.

CRITICAL ORDERING: the vector store is a process-wide singleton created at import
time from `settings.index_dir` / `settings.uploads_dir`. So we redirect those to a
throwaway temp dir via env vars *before* `app` is imported anywhere, keeping the
real `data/index/` untouched. Between tests we reset the singleton so each test
starts from an empty index (self-cleaning, re-runnable).

Only the LLM is mocked (see mocks.py); chunking/embedding/FAISS use the real code.
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
import uuid
from pathlib import Path

import pytest

# --------------------------------------------------------------------------- #
# 1) Make `import app...` work and redirect storage BEFORE importing the app.
# --------------------------------------------------------------------------- #
REPO_ROOT = Path(__file__).resolve().parents[2]
RAG_BACKEND = REPO_ROOT / "rag-backend"
sys.path.insert(0, str(RAG_BACKEND))

_TMP_ROOT = Path(tempfile.mkdtemp(prefix="ragtest_"))
os.environ["INDEX_DIR"] = str(_TMP_ROOT / "index")
os.environ["UPLOADS_DIR"] = str(_TMP_ROOT / "uploads")
# Keep mocked tests from accidentally pointing at anything real.
os.environ.setdefault("LLM_BASE_URL", "http://localhost:8000")
os.environ.setdefault("LLM_API_KEY", "EMPTY")
os.environ.setdefault("LLM_MODEL", "qwen")

# Now it is safe to import the application (singleton store binds to the temp dir).
from app.configs.config import settings           # noqa: E402
from app.main import app                           # noqa: E402
from app.services.vectorstore import store         # noqa: E402
from app.services import ingestion                 # noqa: E402

from fastapi.testclient import TestClient          # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))  # local imports (mocks, fixtures)
from fixtures.make_pdfs import pdf_bytes, KNOWN_ANSWERS    # noqa: E402


def pytest_configure(config):
    config.addinivalue_line("markers", "real_llm: hits the live vLLM server; skipped unless RUN_REAL_LLM=1")


# --------------------------------------------------------------------------- #
# Results recorder -> TEST_RESULTS.md is generated by the run itself.
# Tests call the `record` fixture with input/ideal/actual (+ optional status);
# the runtest hook flips status to FAIL if the test's assertions failed.
# --------------------------------------------------------------------------- #
_RESULTS: dict[str, dict] = {}
_OUTCOME: dict[str, str] = {}


@pytest.fixture
def record(request):
    def _record(tid, area, desc, inp, ideal, actual, status="PASS", note=""):
        _RESULTS[request.node.nodeid] = {
            "id": tid, "area": area, "desc": desc, "input": inp,
            "ideal": ideal, "actual": actual, "status": status, "note": note,
        }
    return _record


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    if rep.when == "call":
        _OUTCOME[item.nodeid] = rep.outcome  # passed / failed
    elif rep.when == "setup" and rep.skipped:
        _OUTCOME[item.nodeid] = "skipped"


def _write_results_md() -> None:
    order = ["Health", "Ingestion", "Chunking", "Embeddings", "Retrieval",
             "Prompt", "Chat", "Validation", "Smoke"]
    rows = list(_RESULTS.values())
    for nodeid, r in _RESULTS.items():
        oc = _OUTCOME.get(nodeid, "unknown")
        if oc == "failed":
            r["status"] = "FAIL"
        elif oc == "skipped":
            r["status"] = "SKIP"
    # also surface tests that failed but never recorded (e.g. errored early)
    counts = {"PASS": 0, "FAIL": 0, "PARTIAL": 0, "SKIP": 0}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    emoji = {"PASS": "✅", "FAIL": "❌", "PARTIAL": "🟡", "SKIP": "⚪"}

    L: list[str] = []
    a = L.append
    import datetime as dt
    a("# RAG Backend — Functional Test Results\n")
    a(f"- **Run at:** {dt.datetime.now():%Y-%m-%d %H:%M:%S}")
    a("- **Scope:** endpoints + pipeline stages in isolation; LLM **mocked** (except the skippable smoke test).")
    a(f"- **Index/uploads:** throwaway temp dir (real `data/index/` untouched).\n")
    a("## Summary\n")
    a("| Status | Count |")
    a("|--------|-------|")
    for k in ("PASS", "FAIL", "PARTIAL", "SKIP"):
        a(f"| {emoji[k]} {k} | {counts.get(k,0)} |")
    a(f"| **Total** | **{len(rows)}** |\n")
    a("| ID | Area | Test | Status |")
    a("|----|------|------|--------|")
    rows_sorted = sorted(rows, key=lambda r: (order.index(r["area"]) if r["area"] in order else 99, r["id"]))
    for r in rows_sorted:
        a(f"| {r['id']} | {r['area']} | {r['desc']} | {emoji.get(r['status'],'?')} {r['status']} |")
    a("\n## Details\n")
    for r in rows_sorted:
        a(f"### {r['id']} — {r['desc']}  {emoji.get(r['status'],'?')} **{r['status']}**\n")
        a(f"- **Input:** {r['input']}")
        a(f"- **Ideal:** {r['ideal']}")
        a(f"- **Actual:** {r['actual']}")
        if r["note"]:
            a(f"- **Note:** {r['note']}")
        a("")
    out = Path(__file__).resolve().parent / "TEST_RESULTS.md"
    out.write_text("\n".join(L), encoding="utf-8")


def pytest_sessionfinish(session, exitstatus):
    try:
        _write_results_md()
    finally:
        shutil.rmtree(_TMP_ROOT, ignore_errors=True)


# --------------------------------------------------------------------------- #
# 2) Per-test reset of the singleton store (empty index + wipe temp files).
# --------------------------------------------------------------------------- #
def _reset_store() -> None:
    with store._lock:
        store.index = store._new_index()
        store.records = {}
        store.next_id = 0
    for p in (settings.faiss_index_path, settings.chunk_store_path):
        Path(p).unlink(missing_ok=True)
    up = Path(settings.uploads_dir)
    if up.exists():
        for f in up.glob("*.pdf"):
            f.unlink(missing_ok=True)


@pytest.fixture(autouse=True)
def reset_store():
    _reset_store()
    yield
    _reset_store()


# --------------------------------------------------------------------------- #
# 3) Handy fixtures/helpers.
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="session")
def client() -> TestClient:
    return TestClient(app)


@pytest.fixture
def session_id() -> str:
    return "sess-" + uuid.uuid4().hex[:12]


@pytest.fixture
def headers(session_id):
    return {"X-Session-Id": session_id}


@pytest.fixture
def make_headers():
    """Factory: build headers for an arbitrary session id."""
    def _make(sid: str) -> dict:
        return {"X-Session-Id": sid}
    return _make


@pytest.fixture
def ingest():
    """Ingest a fixture PDF directly through the real pipeline.

    Returns a callable: ingest(doc_key, session_id, filename=None) -> result dict
    ({doc_id, filename, chunk_count, page_count}).
    """
    def _ingest(doc_key: str, sid: str, filename: str | None = None) -> dict:
        fname = filename or f"{doc_key}.pdf"
        return ingestion.ingest_pdf(pdf_bytes(doc_key), fname, sid)
    return _ingest


# expose modules/objects to tests without re-importing app in every file
@pytest.fixture(scope="session")
def app_store():
    return store


@pytest.fixture(scope="session")
def app_settings():
    return settings
